export const APP_TEXT = {
  tabs: {
    leaderboard: 'Leaderboard',
    upload: 'Upload Match',
    analytics: 'Analytics',
  },
  analytics: {
    title: 'Ranking Graphs',
    playerFilter: 'Player Filter',
    allPlayers: 'All Players',
    matchRankTitle: 'Match-wise Rank (Per Match Points)',
    cumulativeRankTitle: 'Cumulative Rank Progression',
    empty: 'Upload at least one match to see ranking graphs.',
    selectionHint: 'Select one or more players to compare how they move across matches.',
    selectedCount: 'selected',
    selectAll: 'Select all',
    clearAll: 'Clear',
    legendHint: 'Emoji badges make every line easy to spot.',
    noPlayersSelected: 'Choose at least one player to show the graph.',
  },
  hero: {
    badge: 'Match Points Tracker',
    title: 'ScoreKeeper',
    description: 'Upload scoresheet images, track match points, ask in Hindi or English.',
    players: 'Players',
    matches: 'Matches',
    leader: 'Leader',
  },
  leaderboard: {
    title: 'Standings',
    loading: 'Loading standings...',
    export: 'Export',
    total: 'Total',
  },
  upload: {
    title: 'Upload Match',
    changeCode: 'Change Code',
    changeCodeTitle: 'Change Admin Code',
    oldCodePlaceholder: 'Purana / Old code',
    newCodePlaceholder: 'Naya / New code',
    updateCode: 'Update Code',
    adminRequired: 'Admin Code Required',
    enterCodePlaceholder: 'Enter admin code…',
    verifyCode: 'Verify Code',
    selectFile: 'Drop scoresheet image here',
    browseFile: 'or click to browse',
    readImage: 'Read Image',
    scanning: 'Scanning image…',
    review: 'Review extracted scores - edit any points if needed, then confirm.',
    saveSuccess: 'Match saved successfully!',
    leaderboardUpdated: 'Leaderboard has been updated.',
    uploadAnother: 'Upload Another Match',
    imageTooLarge: 'Image is too large. Please use a photo under 3 MB.',
    extractError: 'Extraction failed',
    saveError: 'Save failed',
    notFound: 'not found',
    backToUpload: '← Re-upload',
    confirmSave: 'Confirm & Save',
    saving: 'Saving…',
  },
  chat: {
    title: 'Ask About Scores',
    languageHint: 'Hindi / English',
    open: 'Chat',
    close: 'Hide chat',
    greeting:
      'नमस्ते! 👋 Match points ke baare mein kuch bhi pucho — Hindi ya English mein.\n\n' +
      'Example: "Match 3 mein sabse zyada points kisne liye?" or "Who is in last place?"\n\n' +
      'Admin panel chahiye ho toh bolo: "enable admin panel". Public data ke liye bas pucho: "view all matches data".',
    changeCodePrompt: 'change secret code',
    adminUnlockPrompt: '🔐 Admin panel unlock karne ke liye secret code batao:',
    adminUnlocked: '✅ Admin panel unlocked. You can now view and edit match data below.',
    adminCodeWrong: '❌ Galat admin code hai. Dobara try karo.',
    adminCodeChangePrompt: '🔐 Admin code change karna chahte ho?\nPehle purana / old code batao:',
    oldCodeOk: '✅ Purana code sahi hai!\nAb naya / new code batao:',
    oldCodeWrong: '❌ Galat purana code hai. Dobara try karo ya cancel karne ke liye kuch aur pucho.',
    hintOldCode: 'Purana code type karo — it will be hidden',
    hintNewCode: 'Naya code type karo — it will be hidden',
    placeholderNormal: 'Match 2 mein mere kitne points hain? / Who leads?',
    placeholderOldCode: 'Purana / old code…',
    placeholderNewCode: 'Naya / new code…',
  },
  admin: {
    title: 'Admin Tools',
    description: 'Edit, delete, or reset saved match data.',
    refresh: 'Refresh',
    codeRequired: 'Please enter the admin code first.',
    loadMatchesError: 'Failed to load matches',
    loadMatchError: 'Failed to load match',
    updateMatchError: 'Failed to update match',
    deleteMatchError: 'Failed to delete match',
    resetDataError: 'Failed to reset data',
    adminCodeLabel: 'Admin Code',
    adminCodePlaceholder: 'Enter admin code…',
    adminCodeNote: 'Required for save, delete, and reset actions.',
    savedMatches: 'Saved Matches',
    selectMatch: 'Select a match',
    noMatchSelected: 'No match selected.',
    loadedPrefix: 'Loaded',
    player: 'Player',
    points: 'Points',
    saving: 'Saving…',
    working: 'Working…',
    saveChanges: 'Save Changes',
    deleteMatch: 'Delete Match',
    resetAllData: 'Reset All Data',
    loadMatch: 'Loading match…',
    confirmDelete: 'Delete this match permanently? This cannot be undone.',
    confirmReset: 'Reset all match data? This will remove every saved match and score.',
    loadPrefix: 'Loaded',
  },
} as const;

export const CHAT_INTENTS = {
  changeCode: ['change', 'code'],
  adminUnlock: [
    'enable admin panel',
    'open admin panel',
    'admin panel',
    'unlock admin',
    'secret admin',
  ],
} as const;

export const APP_LIMITS = {
  maxUploadBytes: 3 * 1024 * 1024,
} as const;
